# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: gripper_group
  joint_model_group_pose: open
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_finger_joint
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: gripper_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      left_finger_joint
   - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      [left_finger_joint, right_finger_joint]
    constraints:
      goal_time: 0.6
      # vel_tolerance is 0 for due to the movegroup/follow_joint_trajectory/goal tolerance is empty
      stopped_velocity_tolerance: 0
      left_finger_joint: {trajectory: 0.1, goal: 0.0}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10