joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50
    
wheeltec_gripper_controller:
    type: "effort_controllers/JointPositionController"
    joint: left_finger_joint
    pid: {p: 1.0 , i: 0.0, d: 0.0}