wheeltec:
    joint_limits: # degrees
      left_finger_joint:
        has_position_limits: true
        min_position: 0.7289
        max_position: 0.0
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 0.1
        has_jerk_limits: false
        max_jerk: 0.0
        has_effort_limits: false
        max_effort: 0.0
        min_effort: 0.0